import { PrismaClient } from "@prisma/client";

const prisma = new PrismaClient();

async function main() {
  const now = new Date();
  for (let i = 1; i <= 20; i++) {
    const id = `seed-${i.toString().padStart(2, "0")}`;
    const percentage = Math.round((60 + Math.random() * 40) * 10) / 10;
    const data = {
      school: { name: "Mekun Academy", logoUrl: "/logo_mekun_academy.png" },
      student: { id, name: `Student ${i}`, className: `${(i % 6) + 1}` },
      term: i % 2 === 0 ? "Term 1" : "Term 2",
      date: now.toISOString(),
      teacherName: `Teacher ${(i % 5) + 1}`,
      scores: [
        { indicator: "Problem-Solving Skills", score: 7 + Math.random() * 3 },
        { indicator: "Class Participation", score: 6 + Math.random() * 4 },
      ],
      totalScore: 0,
      percentage,
      comments: "Autogenerated sample",
    };
    // simple total
    data.totalScore = (data.scores as any[]).reduce((a, s) => a + (s.score || 0), 0);

    await prisma.report.upsert({
      where: { id },
      create: {
        id,
        name: (data.student as any).name,
        term: data.term,
        date: new Date(data.date),
        percentage: data.percentage as number,
        data: JSON.stringify(data),
      },
      update: {
        name: (data.student as any).name,
        term: data.term,
        date: new Date(data.date),
        percentage: data.percentage as number,
        data: JSON.stringify(data),
      },
    });
  }
}

main()
  .then(async () => {
    await prisma.$disconnect();
  })
  .catch(async (e) => {
    console.error(e);
    await prisma.$disconnect();
    process.exit(1);
  });
